---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pycontribs/mirrors-prettier
    # keep it before markdownlint and eslint
    rev: "v3.6.2"
    hooks:
      - id: prettier
        always_run: true
        pass_filenames: false
        additional_dependencies:
          - prettier@3.2.4
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
